In [2]:
import numpy as np

In [4]:
# EXERCICIO 01

meu_array = np.arange(10)
print("Array original: ", meu_array)

meu_array[5:9] = 0

print("Array modificado: ", meu_array)

Array original:  [0 1 2 3 4 5 6 7 8 9]
Array modificado:  [0 1 2 3 4 0 0 0 0 9]


In [6]:
# EXERCICIO 02

matriz = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

print(f"Shape da matriz: {matriz.shape}")
print(f"2ª linha da matriz: {matriz[1]}")

Shape da matriz: (3, 2)
2ª linha da matriz: [3 4]


In [8]:
# EXERCICIO 03

matriz = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

print("Matriz completa:")
print(matriz)
print("-" * 20)

coluna_2 = matriz[:, 1]
print(f"2ª coluna da matriz: {coluna_2}")

Matriz completa:
[[1 2]
 [3 4]
 [5 6]]
--------------------
2ª coluna da matriz: [2 4 6]


In [10]:
# EXERCICIO 04

matriz = ([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20]
])

print("Matriz completa:")
print(matriz)
print("-" * 25)

terceira_linha = matriz[2]
print(f"Elementos da 3ª linha: {terceira_linha}")


Matriz completa:
[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]
-------------------------
Elementos da 3ª linha: [11, 12, 13, 14, 15]


In [12]:
#EXERCICIO 05

matriz = np.array([
    [1, 2, 3, 4, 5,],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20]
])

print("Matriz completa:")
print(matriz)
print("-" * 30)

sub_matriz = matriz[0:2, 1:3]

print("Elementos da 1ª e 2ª linhas e 2ª a 3ª colunas:")
print(sub_matriz)

Matriz completa:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
------------------------------
Elementos da 1ª e 2ª linhas e 2ª a 3ª colunas:
[[2 3]
 [7 8]]


In [13]:
#EXERCICIO 06

matriz = np.array([
    [1, 2, 3, 4, 5,],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20]
])

print("Matriz completa:")
print(matriz)
print("-" * 30)

sub_matriz = matriz[1:3, 0:3]

print("Elementos da 2ª e 3ª linhas e 1ª a 3ª colunas:")
print(sub_matriz)

Matriz completa:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
------------------------------
Elementos da 2ª e 3ª linhas e 1ª a 3ª colunas:
[[ 6  7  8]
 [11 12 13]]
